# Generated by Django 4.0.5 on 2022-07-27 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal', '0002_alter_product_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imagen',
            field=models.ImageField(default='coca.png', upload_to='producto_image'),
        ),
    ]
