# Generated by Django 4.0.4 on 2022-08-06 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal', '0003_product_users_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='rol',
            field=models.CharField(default='client', max_length=40),
        ),
    ]
