# Generated by Django 4.0.4 on 2022-07-29 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal', '0004_alter_client_options_alter_client_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='direction',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(default=None, max_length=254),
            preserve_default=False,
        ),
    ]
