# Generated by Django 4.0.4 on 2022-07-30 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal', '0006_remove_client_direction_client_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coments',
            options={'verbose_name': 'coment', 'verbose_name_plural': 'comentarios'},
        ),
    ]
