# Generated by Django 4.0.4 on 2022-07-30 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal', '0007_alter_coments_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coments',
            name='created_at',
        ),
    ]
