# Generated by Django 4.0.4 on 2022-07-31 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal', '0008_remove_coments_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coments',
            name='client',
        ),
        migrations.AddField(
            model_name='coments',
            name='name',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
