# Generated by Django 4.0.4 on 2022-08-04 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal', '0010_product_users_wishlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'product', 'verbose_name_plural': 'productos'},
        ),
    ]
